"""The Analyst Agent.

Its only responsibility is to read the customer's brief and turn it into
explicit, machine-readable software requirements (a requirements engineer).

The rest of the system consumes the output of this agent, so the agent MUST
produce valid JSON with exactly the structure defined below.  The JSON is
generated by Qwen itself -- never assembled by our Python code.
"""

import json

import requests

OLLAMA_URL = "http://127.0.0.1:11434/api/chat"
MODEL = "qwen3:8b"

# The exact keys the JSON contract allows -- nothing more, nothing less.
REQUIRED_KEYS = {"goal", "allowed_actions", "safe_stop", "avoid_obstacles"}

# The only actions the final navigation logic may ever use.
ALLOWED_ACTIONS = ["FORWARD", "LEFT", "RIGHT", "STOP"]

# Qwen can occasionally drift; retry a few times before giving up.
MAX_ATTEMPTS = 3

# ---------------------------------------------------------------------------
# The prompt: role, what the model must do, the constraints it must follow,
# and the final output structure.  This is what makes the agent deterministic.
# ---------------------------------------------------------------------------
SYSTEM_PROMPT = (
    "You are a requirements engineer. "
    "Your only job is to read a customer's brief describing a mobile robot's "
    "navigation and extract explicit, machine-readable software requirements "
    "from it.\n\n"
    "You MUST reply with a single valid JSON object and nothing else "
    "(no markdown, no commentary, no surrounding text).\n\n"
    "The JSON object MUST contain exactly these four keys and no others:\n"
    "{\n"
    '    "goal": "string",\n'
    '    "allowed_actions": ["FORWARD", "LEFT", "RIGHT", "STOP"],\n'
    '    "safe_stop": true,\n'
    '    "avoid_obstacles": true\n'
    "}\n\n"
    "Rules you MUST follow:\n"
    '1. "goal" is a string that states the robot\'s navigation objective in '
    "one sentence (e.g. \"move toward the goal while avoiding obstacles\").\n"
    '2. "allowed_actions" is a list containing EXACTLY these four strings, in '
    'this order: "FORWARD", "LEFT", "RIGHT", "STOP". Do not add or remove any.\n'
    '3. "safe_stop" is a boolean: true if the robot must stop safely when no '
    "safe direction is available, otherwise false.\n"
    '4. "avoid_obstacles" is a boolean: true if the robot must never move into '
    "a blocked direction, otherwise false.\n\n"
    "Do not add any extra keys. The output must be valid JSON."
)


def _call_qwen(messages: list) -> str:
    """Send a conversation to Qwen and return its raw text response."""
    payload = {
        "model": MODEL,
        "messages": messages,
        "stream": False,
        # Low temperature + JSON mode: Qwen is told to emit a JSON object and
        # the runtime enforces it, keeping the output consistent.
        "format": "json",
        "options": {"temperature": 0.0},
    }
    resp = requests.post(OLLAMA_URL, json=payload, timeout=300)
    resp.raise_for_status()
    return resp.json()["message"]["content"]


def validate_requirements(data) -> dict:
    """Validate the requirements produced by Qwen.

    Takes the result already converted into a Python data structure and checks
    that it is a valid dictionary containing exactly the required keys with the
    required types.  Raises ValueError (with a reason) on any violation.
    Returns the validated dictionary on success.
    """
    if not isinstance(data, dict):
        raise ValueError(f"expected a JSON object, got {type(data).__name__}")

    keys = set(data.keys())
    if keys != REQUIRED_KEYS:
        missing = REQUIRED_KEYS - keys
        extra = keys - REQUIRED_KEYS
        raise ValueError(
            f"key mismatch: missing={sorted(missing)} extra={sorted(extra)}"
        )

    if not isinstance(data["goal"], str):
        raise ValueError(f"'goal' must be a string, got {type(data['goal']).__name__}")

    if not isinstance(data["allowed_actions"], list):
        raise ValueError(
            f"'allowed_actions' must be a list, got {type(data['allowed_actions']).__name__}"
        )

    if data["allowed_actions"] != ALLOWED_ACTIONS:
        raise ValueError(
            f"'allowed_actions' must be exactly {ALLOWED_ACTIONS}, "
            f"got {data['allowed_actions']}"
        )

    if not isinstance(data["safe_stop"], bool):
        raise ValueError(
            f"'safe_stop' must be a boolean, got {type(data['safe_stop']).__name__}"
        )

    if not isinstance(data["avoid_obstacles"], bool):
        raise ValueError(
            f"'avoid_obstacles' must be a boolean, got {type(data['avoid_obstacles']).__name__}"
        )

    return data


def run_analyst(brief_text: str) -> dict:
    """Turn the human brief into validated software requirements.

    - accepts the brief text as a parameter (so other code can call it),
    - sends the system prompt + brief to Qwen,
    - accepts Qwen's response,
    - converts the JSON text into Python data (json.loads),
    - validates it,
    - returns the validated requirements.
    """
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": brief_text},
    ]

    last_error = None
    for attempt in range(1, MAX_ATTEMPTS + 1):
        raw = _call_qwen(messages)
        try:
            data = json.loads(raw)  # JSON text -> Python data
            return validate_requirements(data)
        except (json.JSONDecodeError, ValueError) as exc:
            last_error = exc
            print(f"Attempt {attempt}/{MAX_ATTEMPTS} failed: {exc}")

    raise RuntimeError(f"Qwen never produced valid requirements: {last_error}")
